
""" This module provides a collection of brushes to draw GUI elements """

from PyQt6.QtGui import QBrush
from PyQt6.QtCore import Qt

import colours as COLOR


BLUE_I = QBrush(COLOR.INSPECTOR_BLUE)
GREEN_I = QBrush(COLOR.INSPECTOR_GREEN)
YELLOW_I = QBrush(COLOR.INSPECTOR_YELLOW)
RED_I = QBrush(COLOR.INSPECTOR_RED)
WHITE_L = QBrush(COLOR.LABEL_WHITE)
WHITE = QBrush(COLOR.WHITE)
BLACK = QBrush(COLOR.BLACK)
BLUE = QBrush(COLOR.BLUE)
GREY = QBrush(COLOR.GREY)
BLUE_M = QBrush(COLOR.MINEFIELD_BLUE, Qt.BrushStyle.BDiagPattern)
BLUE_L = QBrush(COLOR.LIGHT_BLUE)
RED_D = QBrush(COLOR.DARK_RED)
GREEN = QBrush(COLOR.GREEN)
YELLOW = QBrush(COLOR.YELLOW)
RED = QBrush(COLOR.RED)
RED_M = QBrush(COLOR.MINEFIELD_RED, Qt.BrushStyle.FDiagPattern)
BROWN = QBrush(COLOR.BROWN)
NEUTRAL = QBrush(COLOR.NEUTRAL)
RED_S = QBrush(COLOR.SCANNER_RED)
YELLOW_S = QBrush(COLOR.SCANNER_YELLOW)
YELLOW_M = QBrush(COLOR.MINEFIELD_YELLOW, Qt.BrushStyle.Dense6Pattern)
BLUE_P = QBrush(COLOR.BACKGROUND_BLUE)
RED_P = QBrush(COLOR.BACKGROUND_RED)
YELLOW_P = QBrush(COLOR.BACKGROUND_YELLOW)
GREEN_P = QBrush(COLOR.BACKGROUND_GREEN)
BLUE_F = QBrush(COLOR.FLEET_BLUE)
