
from PyQt6 import QtWidgets, QtGui, QtCore



class Menu(QtWidgets.QMenuBar):
    
    def __init__(self, form):

        super(self.__class__, self).__init__(form)

        MenuFile = QtWidgets.QMenu(self)
        MenuView = QtWidgets.QMenu(self)
        MenuLayout = QtWidgets.QMenu(MenuView)
        MenuZoom = QtWidgets.QMenu(MenuView)
        MenuTurn = QtWidgets.QMenu(self)
        MenuCommands = QtWidgets.QMenu(self)
        MenuReport = QtWidgets.QMenu(self)
        MenuDumpTextFile = QtWidgets.QMenu(MenuReport)
        MenuHelp = QtWidgets.QMenu(self)

        form.actionLoadGame = QtGui.QAction(self)
        form.actionNewGame = QtGui.QAction(self)
        form.actionNewGame.setText("New")
        form.actionNewGame.setStatusTip("Start a new game ...")
        form.actionNewGame.setShortcut("Ctrl+N")
        form.actionNewGame.setAutoRepeat(False)
        form.actionSaveGameAs = QtGui.QAction(self)
        form.actionOpenGame = QtGui.QAction(self)
        form.actionOpenGame.setEnabled(True)
        form.actionOpenGame.setText("Open")
        form.actionOpenGame.setStatusTip("Open a set of game files ...")
        form.actionComputeNewTurn = QtGui.QAction(self)
        form.actionCloseGame = QtGui.QAction(self)
        form.actionCloseGame.setText("Close")
        form.actionCloseGame.setStatusTip("Close the current game ...")
        form.actionCloseGame.setAutoRepeat(False)
        form.actionSaveGame = QtGui.QAction(self)
        form.actionSaveGame.setText("Save")
        form.actionSaveGame.setStatusTip("Save the current turn to a set of game files ...")
        form.actionSaveGame.setShortcut("Ctrl+S")
        form.actionSaveGame.setAutoRepeat(False)
        form.actionExit = QtGui.QAction(self)
        form.actionExit.setText("Exit")
        form.actionExit.setStatusTip("Exit")
        form.actionExit.setShortcut("Ctrl+X")
        form.actionExit.setAutoRepeat(False)
        form.actionShowToolbar = QtGui.QAction(self)
        form.actionGameParameters = QtGui.QAction(self)
        form.actionCompute = QtGui.QAction(self)
        form.actionGenerate = QtGui.QAction(self)
        form.actionGenerate.setText("Generate")
        form.actionGenerate.setStatusTip("Generate a new turn ...")
        form.actionGenerate.setAutoRepeat(False)
        form.actionToolbar = QtGui.QAction(self)
        form.actionToolbar.setCheckable(True)
        form.actionToolbar.setChecked(True)
        form.actionDefault = QtGui.QAction(self)
        form.actionRace = QtGui.QAction(self)
        form.action25 = QtGui.QAction(self)
        form.action25.setCheckable(True)
        form.action50 = QtGui.QAction(self)
        form.action50.setCheckable(True)
        form.action75 = QtGui.QAction(self)
        form.action75.setCheckable(True)
        form.action100 = QtGui.QAction(self)
        form.action100.setCheckable(True)
        form.action100.setChecked(True)
        form.action125 = QtGui.QAction(self)
        form.action125.setCheckable(True)
        form.action150 = QtGui.QAction(self)
        form.action150.setCheckable(True)
        form.action200 = QtGui.QAction(self)
        form.action200.setCheckable(True)
        form.action400 = QtGui.QAction(self)
        form.action400.setCheckable(True)
        form.actionSaveSubmit = QtGui.QAction(self)
        form.actionSaveSubmit.setText("Save and Submit")
        form.actionSaveSubmit.setStatusTip("Save Game & submit Your turn ...")
        form.actionSaveSubmit.setShortcut("Ctrl+A")
        form.actionSaveSubmit.setAutoRepeat(False)
        form.actionShipDesign = QtGui.QAction(self)
        form.actionBattlePlans = QtGui.QAction(self)
        form.actionPlayerRelations = QtGui.QAction(self)
        form.actionPlayerRelations.setIconVisibleInMenu(False)
        form.actionResearch = QtGui.QAction(self)
        form.actionChangePassword = QtGui.QAction(self)
        form.actionPlanets = QtGui.QAction(self)
        form.actionPlanets.setShortcut("F3")
        form.actionPlanets.setAutoRepeat(False)
        form.actionPlanets.setIconVisibleInMenu(False)
        form.actionPlanets.setShortcutVisibleInContextMenu(False)
        form.actionFleets = QtGui.QAction(self)
        form.actionFleets.setAutoRepeat(False)
        form.actionFleets.setIconVisibleInMenu(False)
        form.actionOtherFleets = QtGui.QAction(self)
        form.actionOtherFleets.setShortcut("F3")
        form.actionOtherFleets.setAutoRepeat(False)
        form.actionOtherFleets.setIconVisibleInMenu(False)
        form.actionOtherFleets.setShortcutVisibleInContextMenu(False)
        form.actionBattles = QtGui.QAction(self)
        form.actionBattles.setShortcut("F3")
        form.actionBattles.setAutoRepeat(False)
        form.actionBattles.setIconVisibleInMenu(False)
        form.actionScore = QtGui.QAction(self)
        form.actionScore.setShortcut("F10")
        form.actionScore.setAutoRepeat(False)
        form.actionScore.setIconVisibleInMenu(False)
        form.actionUniverseDefinition = QtGui.QAction(self)
        form.actionUniverseDefinition.setIconVisibleInMenu(False)
        form.actionPlanetInformation = QtGui.QAction(self)
        form.actionPlanetInformation.setIconVisibleInMenu(False)
        form.actionFleetInformation = QtGui.QAction(form)
        form.actionFleetInformation.setIconVisibleInMenu(False)

        MenuFile.addAction(form.actionNewGame)
        MenuFile.addAction(form.actionOpenGame)
        MenuFile.addAction(form.actionCloseGame)
        MenuFile.addAction(form.actionSaveGame)
        MenuFile.addAction(form.actionSaveSubmit)
        MenuFile.addSeparator()
        MenuFile.addAction(form.actionExit)
        MenuLayout.addAction(form.actionDefault)
        MenuZoom.addAction(form.action25)
        MenuZoom.addAction(form.action50)
        MenuZoom.addAction(form.action75)
        MenuZoom.addAction(form.action100)
        MenuZoom.addAction(form.action125)
        MenuZoom.addAction(form.action150)
        MenuZoom.addAction(form.action200)
        MenuZoom.addAction(form.action400)
        MenuView.addAction(form.actionToolbar)
        MenuView.addAction(MenuLayout.menuAction())
        MenuView.addAction(MenuZoom.menuAction())
        MenuView.addSeparator()
        MenuView.addAction(form.actionRace)
        MenuTurn.addAction(form.actionGenerate)
        MenuCommands.addAction(form.actionShipDesign)
        MenuCommands.addAction(form.actionResearch)
        MenuCommands.addAction(form.actionBattlePlans)
        MenuCommands.addAction(form.actionPlayerRelations)
        MenuCommands.addSeparator()
        MenuCommands.addAction(form.actionChangePassword)
        MenuDumpTextFile.addAction(form.actionUniverseDefinition)
        MenuDumpTextFile.addAction(form.actionPlanetInformation)
        MenuDumpTextFile.addAction(form.actionFleetInformation)
        MenuReport.addAction(form.actionPlanets)
        MenuReport.addAction(form.actionFleets)
        MenuReport.addAction(form.actionOtherFleets)
        MenuReport.addSeparator()
        MenuReport.addAction(form.actionBattles)
        MenuReport.addSeparator()
        MenuReport.addAction(form.actionScore)
        MenuReport.addSeparator()
        MenuReport.addAction(MenuDumpTextFile.menuAction())

        MenuFile.setTitle("File")
        MenuView.setTitle("View")
        MenuLayout.setTitle("Layout")
        MenuZoom.setTitle("Zoom")
        MenuTurn.setTitle("Turn")
        MenuCommands.setTitle("Commands")
        MenuReport.setTitle("Report")
        MenuDumpTextFile.setTitle("Dump to text file")
        MenuHelp.setTitle("Help")

        self.addAction(MenuFile.menuAction())
        self.addAction(MenuView.menuAction())
        self.addAction(MenuTurn.menuAction())
        self.addAction(MenuCommands.menuAction())
        self.addAction(MenuReport.menuAction())
        self.addAction(MenuHelp.menuAction())