
from PyQt6 import QtGui, QtWidgets, QtCore
from PyQt6.QtCore import Qt



class ToolBar(QtWidgets.QToolBar):

    def __init__(self, form):

        super(self.__class__, self).__init__()

        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Default"))
        form.actionDefaultView = QtGui.QAction(self)
        form.actionDefaultView.setCheckable(True)
        form.actionDefaultView.setIcon(Icon)
        form.actionDefaultView.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Percent"))
        form.actionPercentView = QtGui.QAction(self)
        form.actionPercentView.setCheckable(True)
        form.actionPercentView.setIcon(Icon)
        form.actionPercentView.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/People"))
        form.actionPopulationView = QtGui.QAction(self)
        form.actionPopulationView.setCheckable(True)
        form.actionPopulationView.setIcon(Icon)
        form.actionPopulationView.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Surface"))
        form.actionSurfaceMineralView = QtGui.QAction(self)
        form.actionSurfaceMineralView.setCheckable(True)
        form.actionSurfaceMineralView.setIcon(Icon)
        form.actionSurfaceMineralView.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Minerals"))
        form.actionConcentrationView = QtGui.QAction(self)
        form.actionConcentrationView.setCheckable(True)
        form.actionConcentrationView.setIcon(Icon)
        form.actionConcentrationView.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Cancel"))
        form.actionNoInfoView = QtGui.QAction(self)
        form.actionNoInfoView.setCheckable(True)
        form.actionNoInfoView.setIcon(Icon)
        form.actionNoInfoView.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Waypoint"))
        form.actionAddWaypoint = QtGui.QAction(self)
        form.actionAddWaypoint.setCheckable(True)
        form.actionAddWaypoint.setIcon(Icon)
        form.actionAddWaypoint.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Waiting"))
        form.actionWaitingFleets = QtGui.QAction(self)
        form.actionWaitingFleets.setCheckable(True)
        form.actionWaitingFleets.setIcon(Icon)
        form.actionWaitingFleets.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Orbiting"))
        form.actionShipCount = QtGui.QAction(self)
        form.actionShipCount.setCheckable(True)
        form.actionShipCount.setIcon(Icon)
        form.actionShipCount.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Friendlies"))
        form.actionFriendlies = QtGui.QAction(self)
        form.actionFriendlies.setCheckable(True)
        form.actionFriendlies.setIcon(Icon)
        form.actionFriendlies.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Names"))
        form.actionFoes = QtGui.QAction(self)
        form.actionFoes.setCheckable(True)
        form.actionFoes.setIcon(Icon)
        form.actionFoes.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Foes"))
        form.actionFoes = QtGui.QAction(self)
        form.actionFoes.setCheckable(True)
        form.actionFoes.setIcon(Icon)
        form.actionFoes.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Zoomlevel"))
        form.actionZoom = QtGui.QAction(self)
        form.actionZoom.setIcon(Icon)
        form.actionZoom.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Paths"))
        form.actionPathOverlay = QtGui.QAction(self)
        form.actionPathOverlay.setCheckable(True)
        form.actionPathOverlay.setIcon(Icon)
        form.actionPathOverlay.setAutoRepeat(False)
#
        Icon = QtGui.QIcon()
        Icon.addPixmap(QtGui.QPixmap(":/Toolbar/Names"))
        form.actionPlanetNames = QtGui.QAction(self)
        form.actionPlanetNames.setCheckable(True)
        form.actionPlanetNames.setIcon(Icon)
        form.actionPlanetNames.setAutoRepeat(False)
#
        form.RadarRange = QtWidgets.QSpinBox()
        form.RadarRange.setSuffix('%')
        form.RadarRange.setRange(10, 100)
        form.RadarRange.setValue(100)
        form.RadarRange.setSingleStep(10)
        form.RadarRange.setMinimumSize(QtCore.QSize(100, 40))
        form.RadarRange.setAlignment(Qt.AlignmentFlag.AlignRight)
        form.RadarRange.adjustSize()
#
        self.addAction(form.actionDefaultView)
        self.addAction(form.actionSurfaceMineralView)
        self.addAction(form.actionConcentrationView)
        self.addAction(form.actionPercentView)
        self.addAction(form.actionPopulationView)
        self.addAction(form.actionNoInfoView)
        self.addAction(form.actionAddWaypoint)
        self.addWidget(form.RadarRange)
        self.addAction(form.actionPathOverlay)
        self.addAction(form.actionPlanetNames)
        self.addAction(form.actionShipCount)
        self.addAction(form.actionWaitingFleets)
        self.addAction(form.actionFriendlies)
        self.addAction(form.actionFoes)
        self.addAction(form.actionZoom)
